package com.churchmanagement.service;

import com.churchmanagement.dto.DatabaseSetupDto;
import com.churchmanagement.exception.DatabaseException;

import java.io.IOException;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Properties;

public class DatabaseSetupService {

    // createDatabaseIfNotExist is intentionally omitted: in a multi-machine
    // deployment the database is created by the DBA before first use, and the
    // app user typically has no CREATE privilege at server level.  Including
    // that flag causes MySQL Connector/J to issue "CREATE DATABASE IF NOT
    // EXISTS" on every connection, which MySQL rejects with "Access denied"
    // even when the user's credentials are correct.
    private static final String URL_OPTIONS =
            "useUnicode=true"
            + "&characterEncoding=utf8"
            + "&connectionCollation=utf8mb4_unicode_ci"
            + "&serverTimezone=UTC";

    /**
     * Returns {@code false} only when the app is running as a packaged install
     * ({@code app.home} is set) and no external {@code application.properties}
     * exists yet.  In dev / IDE mode ({@code app.home} absent) always returns
     * {@code true} so the setup screen is skipped.
     */
    public boolean isConfigured() {
        String appHome = System.getProperty("app.home");
        if (appHome == null) {
            return true;
        }
        return Files.exists(externalPropertiesPath(appHome));
    }

    /**
     * Loads the current saved configuration into a DTO.
     * Returns a DTO filled with sensible defaults when no file exists yet.
     */
    public DatabaseSetupDto load() {
        DatabaseSetupDto dto = new DatabaseSetupDto();
        String appHome = System.getProperty("app.home");
        if (appHome == null) {
            return dto;
        }
        Path path = externalPropertiesPath(appHome);
        if (!Files.exists(path)) {
            return dto;
        }
        try {
            Properties p = new Properties();
            try (var in = Files.newInputStream(path)) {
                p.load(in);
            }
            dto.setHost(firstNonBlank(p.getProperty("db.host"), dto.getHost()));
            dto.setPort(parsePort(p.getProperty("db.port"), dto.getPort()));
            dto.setDatabaseName(firstNonBlank(p.getProperty("db.name"), dto.getDatabaseName()));
            dto.setUsername(firstNonBlank(p.getProperty("db.username"), dto.getUsername()));
            dto.setPassword(firstNonBlank(p.getProperty("db.password"), dto.getPassword()));
            dto.setRunMigrations(!"false".equalsIgnoreCase(p.getProperty("db.run-migrations", "true")));
        } catch (IOException ignored) {
            // Return defaults — the setup screen will let the user correct anything.
        }
        return dto;
    }

    /**
     * Writes a complete {@code application.properties} to {@code $app.home}.
     * All non-UI keys (pool settings, Flyway, etc.) are set to production
     * defaults so the file is always fully populated after setup.
     */
    public void save(DatabaseSetupDto dto) {
        String appHome = System.getProperty("app.home");
        if (appHome == null) {
            throw new DatabaseException("Cannot save configuration: app.home system property is not set.");
        }
        Path path = externalPropertiesPath(appHome);
        Properties p = buildProperties(dto);
        try (OutputStream out = Files.newOutputStream(path)) {
            p.store(out, "Church Management System — machine configuration (generated by setup wizard)");
        } catch (IOException e) {
            throw new DatabaseException("Failed to write configuration file: " + path, e);
        }
    }

    /**
     * Tests the credentials in {@code dto} without touching the application's
     * singleton DataSource.
     *
     * <p>Uses a plain {@link DriverManager} call so MySQL errors (Access denied,
     * Unknown database, etc.) surface immediately instead of timing out inside a
     * HikariCP retry loop.  TCP connect and socket timeouts are embedded in the
     * URL so an unreachable host still fails within ~8 seconds.</p>
     *
     * @throws DatabaseException with a user-friendly message on failure.
     */
    public void testConnection(DatabaseSetupDto dto) {
        // connectTimeout / socketTimeout are MySQL Connector/J URL params (milliseconds).
        // They ensure an unreachable host fails quickly without HikariCP retries.
        String testUrl = buildJdbcUrl(dto) + "&connectTimeout=8000&socketTimeout=10000";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try (Connection conn = DriverManager.getConnection(testUrl, dto.getUsername(), dto.getPassword())) {
                if (!conn.isValid(5)) {
                    throw new DatabaseException("Connection validation failed — server responded but the connection is not usable.");
                }
            }
        } catch (DatabaseException e) {
            throw e;
        } catch (Exception e) {
            throw new DatabaseException(friendlyMessage(e), e);
        }
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private Properties buildProperties(DatabaseSetupDto dto) {
        Properties p = new Properties();

        // JDBC connection
        p.setProperty("db.driver",   "com.mysql.cj.jdbc.Driver");
        p.setProperty("db.url",      buildJdbcUrl(dto));
        p.setProperty("db.username", dto.getUsername());
        p.setProperty("db.password", dto.getPassword());

        // Individual fields — used by BackupCommandBuilder for mysqldump / mysql CLI
        p.setProperty("db.host", dto.getHost());
        p.setProperty("db.port", String.valueOf(dto.getPort()));
        p.setProperty("db.name", dto.getDatabaseName());
        p.setProperty("db.user", dto.getUsername());

        // HikariCP pool (production defaults; connection-timeout tightened for LAN)
        p.setProperty("db.pool.name",               "ChurchManagementPool");
        p.setProperty("db.pool.minimum-idle",        "2");
        p.setProperty("db.pool.maximum-size",        "10");
        p.setProperty("db.pool.connection-timeout",  "10000");
        p.setProperty("db.pool.idle-timeout",        "600000");
        p.setProperty("db.pool.max-lifetime",        "1800000");

        // Flyway
        p.setProperty("flyway.locations", "classpath:db/migration");

        // Migration control — only the designated primary machine should run migrations.
        p.setProperty("db.run-migrations", dto.isRunMigrations() ? "true" : "false");

        // Misc
        p.setProperty("receipt.pdf.output.folder", "./receipts");

        return p;
    }

    private String buildJdbcUrl(DatabaseSetupDto dto) {
        return "jdbc:mysql://" + dto.getHost() + ":" + dto.getPort()
                + "/" + dto.getDatabaseName() + "?" + URL_OPTIONS;
    }

    private int parsePort(String value, int defaultPort) {
        if (value == null || value.isBlank()) return defaultPort;
        try {
            return Integer.parseInt(value.strip());
        } catch (NumberFormatException e) {
            return defaultPort;
        }
    }

    private String firstNonBlank(String value, String fallback) {
        return (value == null || value.isBlank()) ? fallback : value.strip();
    }

    private Path externalPropertiesPath(String appHome) {
        return Path.of(appHome, "application.properties");
    }

    private String friendlyMessage(Exception e) {
        String msg      = e.getMessage() == null ? "" : e.getMessage();
        Throwable cause = e.getCause();
        String causeMsg = cause == null ? "" : (cause.getMessage() == null ? "" : cause.getMessage());
        String combined = msg + " " + causeMsg;

        if (combined.contains("Communications link failure") || combined.contains("Connection refused")) {
            return "Cannot reach the server. Check the host and port.";
        }
        if (combined.contains("CREATE command denied") || combined.contains("create command denied")) {
            return "The database user lacks CREATE privilege. Grant the necessary privileges, or ask your DBA to create the database manually before connecting.";
        }
        if (combined.contains("Access denied")) {
            return "Access denied — check the username and password.";
        }
        if (combined.contains("Unknown database")) {
            return "Database not found — check the database name.";
        }
        if (combined.contains("Unable to acquire JDBC Connection") || combined.contains("Connection is not available")) {
            return "Connection timed out. Check the host and port, and ensure MySQL is running.";
        }
        return msg.length() > 180 ? msg.substring(0, 180) + "…" : msg;
    }
}
