app.name=Church Management System

db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://192.168.1.101:3306/church_management_system?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=UTC
db.username=churchDbUser
db.password=church@091309
db.host=192.168.1.101
db.port=3306
db.name=church_management_system
db.user=churchDbUser
db.pool.name=ChurchManagementPool
db.pool.minimum-idle=2
db.pool.maximum-size=10
db.pool.connection-timeout=30000
db.pool.idle-timeout=600000
db.pool.max-lifetime=1800000
# Only true on the designated "primary" client/server (e.g. Client 1)
db.run-migrations=true

flyway.locations=classpath:db/migration

receipt.pdf.output.folder=./receipts
reports.export.folder=./reports
backup.folder=./backups
backup.mysqldump.path=
backup.mysql.client.path=

# Mysql Server admin user
db.admin.username=root
db.admin.password=asd@1234