app.name=Church Management System

db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/church_management_system?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=UTC
db.username=root
db.password=asd@1234
db.pool.name=ChurchManagementPool
db.pool.minimum-idle=2
db.pool.maximum-size=10
db.pool.connection-timeout=30000
db.pool.idle-timeout=600000
db.pool.max-lifetime=1800000

flyway.locations=classpath:db/migration

receipt.pdf.output.folder=./receipts
